baseURL = "https://savoirarchitecture.co.uk/"
languageCode = "en-gb"
title = "Savoir Architecture"

[params]
  description = "Knowledge in Architecture"
  email = "info@savoirarchitecture.co.uk"
  tel = "07747 465 927"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
